### ISSUE TITLE
.webp Filename extension

### ISSUE THREAD

**Issue by thisconnect** [imagemin/imagemin-webp#9]
If you using imagemin-webp as described in the readme, the resulting files still have the original filename extensions (jpg and png). Official filename extension for WebP is .webp 

Can jpg's or png's use webp encoding or should they have .webp extension?

```javascript
const imagemin = require('imagemin');
const imageminWebp = require('imagemin-webp');

imagemin(['images/*.{jpg,png}'], 'build/images', {
    use: [
        imageminWebp({quality: 50})
    ]
}).then(() => {
    console.log('Images optimized');
});
```

sorry for opening so many issues

**Comment by kevva** [comment]
This plugin only accept and returns a buffer. The extension handling should be done in `imagemin`. I'll fix it.

**Comment by kevva** [comment]
Fixed in https://github.com/imagemin/imagemin/commit/d287715df9f583b6ea12999dfe377ec6e7247db6.

**Comment by thisconnect** [comment]
hm.. I somehow still get jpg and png. Is the readme example or my test still correct?

**Comment by kevva** [comment]
Did `imagemin-webp` install correctly?

**Comment by thisconnect** [comment]
I think so did you do an update since yesterday?

```
rm -rf node_modules/
$ npm i imagemin-webp
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

> cwebp-bin@3.1.0 postinstall /Users/me/project/node_modules/cwebp-bin
> node lib/install.js

  ✔ cwebp pre-build test passed successfully
project@1.0.0 /Users/me/project
└─┬ imagemin-webp@4.0.0 
  ├─┬ cwebp-bin@3.1.0 
  │ ├─┬ bin-build@2.2.0 
  │ │ ├─┬ archive-type@3.2.0 
  │ │ │ └── file-type@3.8.0 
  │ │ ├─┬ decompress@3.0.0 
  │ │ │ ├─┬ buffer-to-vinyl@1.1.0 
  │ │ │ │ └── file-type@3.8.0 
  │ │ │ ├─┬ concat-stream@1.5.1 
  │ │ │ │ ├── inherits@2.0.1 
  │ │ │ │ ├── readable-stream@2.0.6 
  │ │ │ │ └── typedarray@0.0.6 
  │ │ │ ├─┬ decompress-tar@3.1.0 
  │ │ │ │ ├── is-tar@1.0.0 
  │ │ │ │ ├── object-assign@2.1.1 
  │ │ │ │ ├─┬ strip-dirs@1.1.1 
  │ │ │ │ │ ├─┬ is-absolute@0.1.7 
  │ │ │ │ │ │ └── is-relative@0.1.3 
  │ │ │ │ │ ├── is-natural-number@2.1.1 
  │ │ │ │ │ └── sum-up@1.0.3 
  │ │ │ │ ├─┬ tar-stream@1.5.2 
  │ │ │ │ │ ├─┬ bl@1.1.2 
  │ │ │ │ │ │ └── readable-stream@2.0.6 
  │ │ │ │ │ ├── end-of-stream@1.1.0 
  │ │ │ │ │ └── xtend@4.0.1 
  │ │ │ │ ├─┬ through2@0.6.5 
  │ │ │ │ │ └─┬ readable-stream@1.0.34 
  │ │ │ │ │   └── isarray@0.0.1 
  │ │ │ │ └─┬ vinyl@0.4.6 
  │ │ │ │   └── clone@0.2.0 
  │ │ │ ├─┬ decompress-tarbz2@3.1.0 
  │ │ │ │ ├── is-bzip2@1.0.0 
  │ │ │ │ ├─┬ seek-bzip@1.0.5 
  │ │ │ │ │ └─┬ commander@2.8.1 
  │ │ │ │ │   └── graceful-readlink@1.0.1 
  │ │ │ │ └─┬ vinyl@0.4.6 
  │ │ │ │   └── clone@0.2.0 
  │ │ │ ├─┬ decompress-targz@3.1.0 
  │ │ │ │ ├── is-gzip@1.0.0 
  │ │ │ │ └─┬ vinyl@0.4.6 
  │ │ │ │   └── clone@0.2.0 
  │ │ │ ├─┬ decompress-unzip@3.4.0 
  │ │ │ │ ├── is-zip@1.0.0 
  │ │ │ │ ├── stat-mode@0.2.1 
  │ │ │ │ ├─┬ through2@2.0.1 
  │ │ │ │ │ └── readable-stream@2.0.6 
  │ │ │ │ └─┬ yauzl@2.4.2 
  │ │ │ │   └─┬ fd-slicer@1.0.1 
  │ │ │ │     └── pend@1.2.0 
  │ │ │ ├─┬ stream-combiner2@1.1.1 
  │ │ │ │ └── duplexer2@0.1.4 
  │ │ │ ├─┬ vinyl-assign@1.2.1 
  │ │ │ │ └── object-assign@4.1.0 
  │ │ │ └─┬ vinyl-fs@2.4.3 
  │ │ │   ├─┬ duplexify@3.4.3 
  │ │ │   │ └── end-of-stream@1.0.0 
  │ │ │   ├─┬ glob-stream@5.3.2 
  │ │ │   │ ├── extend@3.0.0 
  │ │ │   │ ├── glob@5.0.15 
  │ │ │   │ ├─┬ glob-parent@2.0.0 
  │ │ │   │ │ └── is-glob@2.0.1 
  │ │ │   │ ├─┬ micromatch@2.3.8 
  │ │ │   │ │ ├─┬ arr-diff@2.0.0 
  │ │ │   │ │ │ └── arr-flatten@1.0.1 
  │ │ │   │ │ ├── array-unique@0.2.1 
  │ │ │   │ │ ├─┬ braces@1.8.5 
  │ │ │   │ │ │ ├─┬ expand-range@1.8.2 
  │ │ │   │ │ │ │ └─┬ fill-range@2.2.3 
  │ │ │   │ │ │ │   ├── is-number@2.1.0 
  │ │ │   │ │ │ │   ├── isobject@2.1.0 
  │ │ │   │ │ │ │   ├── randomatic@1.1.5 
  │ │ │   │ │ │ │   └── repeat-string@1.5.4 
  │ │ │   │ │ │ ├── preserve@0.2.0 
  │ │ │   │ │ │ └── repeat-element@1.1.2 
  │ │ │   │ │ ├─┬ expand-brackets@0.1.5 
  │ │ │   │ │ │ └── is-posix-bracket@0.1.1 
  │ │ │   │ │ ├── extglob@0.3.2 
  │ │ │   │ │ ├── filename-regex@2.0.0 
  │ │ │   │ │ ├── is-extglob@1.0.0 
  │ │ │   │ │ ├─┬ kind-of@3.0.3 
  │ │ │   │ │ │ └── is-buffer@1.1.3 
  │ │ │   │ │ ├── normalize-path@2.0.1 
  │ │ │   │ │ ├─┬ object.omit@2.0.0 
  │ │ │   │ │ │ ├─┬ for-own@0.1.4 
  │ │ │   │ │ │ │ └── for-in@0.1.5 
  │ │ │   │ │ │ └── is-extendable@0.1.1 
  │ │ │   │ │ ├─┬ parse-glob@3.0.4 
  │ │ │   │ │ │ ├── glob-base@0.3.0 
  │ │ │   │ │ │ └── is-dotfile@1.0.2 
  │ │ │   │ │ └─┬ regex-cache@0.4.3 
  │ │ │   │ │   ├── is-equal-shallow@0.1.3 
  │ │ │   │ │   └── is-primitive@2.0.0 
  │ │ │   │ ├── ordered-read-streams@0.3.0 
  │ │ │   │ ├─┬ to-absolute-glob@0.1.1 
  │ │ │   │ │ └── extend-shallow@2.0.1 
  │ │ │   │ └─┬ unique-stream@2.2.1 
  │ │ │   │   └─┬ json-stable-stringify@1.0.1 
  │ │ │   │     └── jsonify@0.0.0 
  │ │ │   ├── graceful-fs@4.1.4 
  │ │ │   ├─┬ gulp-sourcemaps@1.6.0 
  │ │ │   │ ├── convert-source-map@1.2.0 
  │ │ │   │ └─┬ through2@2.0.1 
  │ │ │   │   └── readable-stream@2.0.6 
  │ │ │   ├── is-valid-glob@0.3.0 
  │ │ │   ├── lazystream@1.0.0 
  │ │ │   ├─┬ lodash.isequal@4.2.0 
  │ │ │   │ ├── lodash._root@3.0.1 
  │ │ │   │ └── lodash.keys@4.0.7 
  │ │ │   ├── merge-stream@1.0.0 
  │ │ │   ├─┬ mkdirp@0.5.1 
  │ │ │   │ └── minimist@0.0.8 
  │ │ │   ├── object-assign@4.1.0 
  │ │ │   ├─┬ strip-bom@2.0.0 
  │ │ │   │ └── is-utf8@0.2.1 
  │ │ │   ├─┬ strip-bom-stream@1.0.0 
  │ │ │   │ └── first-chunk-stream@1.0.0 
  │ │ │   ├─┬ through2@2.0.1 
  │ │ │   │ └── readable-stream@2.0.6 
  │ │ │   ├─┬ through2-filter@2.0.0 
  │ │ │   │ └─┬ through2@2.0.1 
  │ │ │   │   └── readable-stream@2.0.6 
  │ │ │   └── vali-date@1.0.0 
  │ │ ├─┬ download@4.4.3 
  │ │ │ ├─┬ caw@1.2.0 
  │ │ │ │ ├─┬ get-proxy@1.1.0 
  │ │ │ │ │ └─┬ rc@1.1.6 
  │ │ │ │ │   ├── deep-extend@0.4.1 
  │ │ │ │ │   ├── ini@1.3.4 
  │ │ │ │ │   └── strip-json-comments@1.0.4 
  │ │ │ │ ├── is-obj@1.0.1 
  │ │ │ │ ├── object-assign@3.0.0 
  │ │ │ │ └── tunnel-agent@0.4.3 
  │ │ │ ├─┬ filenamify@1.2.1 
  │ │ │ │ ├── filename-reserved-regex@1.0.0 
  │ │ │ │ ├── strip-outer@1.0.0 
  │ │ │ │ └── trim-repeated@1.0.0 
  │ │ │ ├─┬ got@5.6.0 
  │ │ │ │ ├─┬ create-error-class@3.0.2 
  │ │ │ │ │ └── capture-stack-trace@1.0.0 
  │ │ │ │ ├── is-plain-obj@1.1.0 
  │ │ │ │ ├── is-redirect@1.0.0 
  │ │ │ │ ├── is-retry-allowed@1.0.0 
  │ │ │ │ ├── is-stream@1.1.0 
  │ │ │ │ ├── lowercase-keys@1.0.0 
  │ │ │ │ ├── node-status-codes@1.0.0 
  │ │ │ │ ├── object-assign@4.1.0 
  │ │ │ │ ├─┬ parse-json@2.2.0 
  │ │ │ │ │ └─┬ error-ex@1.3.0 
  │ │ │ │ │   └── is-arrayish@0.2.1 
  │ │ │ │ ├─┬ pinkie-promise@2.0.1 
  │ │ │ │ │ └── pinkie@2.0.4 
  │ │ │ │ ├── timed-out@2.0.0 
  │ │ │ │ ├── unzip-response@1.0.0 
  │ │ │ │ └─┬ url-parse-lax@1.0.0 
  │ │ │ │   └── prepend-http@1.0.4 
  │ │ │ ├─┬ gulp-decompress@1.2.0 
  │ │ │ │ └─┬ gulp-util@3.0.7 
  │ │ │ │   ├── array-differ@1.0.0 
  │ │ │ │   ├── array-uniq@1.0.2 
  │ │ │ │   ├── beeper@1.1.0 
  │ │ │ │   ├── dateformat@1.0.12 
  │ │ │ │   ├─┬ fancy-log@1.2.0 
  │ │ │ │   │ └── time-stamp@1.0.1 
  │ │ │ │   ├─┬ gulplog@1.0.0 
  │ │ │ │   │ └── glogg@1.0.0 
  │ │ │ │   ├─┬ has-gulplog@0.1.0 
  │ │ │ │   │ └── sparkles@1.0.0 
  │ │ │ │   ├── lodash._reescape@3.0.0 
  │ │ │ │   ├── lodash._reevaluate@3.0.0 
  │ │ │ │   ├── lodash._reinterpolate@3.0.0 
  │ │ │ │   ├─┬ lodash.template@3.6.2 
  │ │ │ │   │ ├── lodash._basecopy@3.0.1 
  │ │ │ │   │ ├── lodash._basetostring@3.0.1 
  │ │ │ │   │ ├── lodash._basevalues@3.0.0 
  │ │ │ │   │ ├── lodash._isiterateecall@3.0.9 
  │ │ │ │   │ ├── lodash.escape@3.2.0 
  │ │ │ │   │ ├─┬ lodash.keys@3.1.2 
  │ │ │ │   │ │ ├── lodash._getnative@3.9.1 
  │ │ │ │   │ │ ├── lodash.isarguments@3.0.8 
  │ │ │ │   │ │ └── lodash.isarray@3.0.4 
  │ │ │ │   │ ├── lodash.restparam@3.6.1 
  │ │ │ │   │ └── lodash.templatesettings@3.1.1 
  │ │ │ │   ├─┬ multipipe@0.1.2 
  │ │ │ │   │ └─┬ duplexer2@0.0.2 
  │ │ │ │   │   └─┬ readable-stream@1.1.14 
  │ │ │ │   │     └── isarray@0.0.1 
  │ │ │ │   ├── object-assign@3.0.0 
  │ │ │ │   ├─┬ through2@2.0.1 
  │ │ │ │   │ └── readable-stream@2.0.6 
  │ │ │ │   └── vinyl@0.5.3 
  │ │ │ ├── gulp-rename@1.2.2 
  │ │ │ ├── is-url@1.2.1 
  │ │ │ ├── object-assign@4.1.0 
  │ │ │ ├── read-all-stream@3.1.0 
  │ │ │ ├─┬ readable-stream@2.1.4 
  │ │ │ │ ├── buffer-shims@1.0.0 
  │ │ │ │ ├── core-util-is@1.0.2 
  │ │ │ │ ├── isarray@1.0.0 
  │ │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ │ ├── string_decoder@0.10.31 
  │ │ │ │ └── util-deprecate@1.0.2 
  │ │ │ ├─┬ vinyl@1.1.1 
  │ │ │ │ ├── clone@1.0.2 
  │ │ │ │ ├── clone-stats@0.0.1 
  │ │ │ │ └── replace-ext@0.0.1 
  │ │ │ └─┬ ware@1.3.0 
  │ │ │   └─┬ wrap-fn@0.1.5 
  │ │ │     └── co@3.1.0 
  │ │ ├─┬ exec-series@1.0.2 
  │ │ │ └── async-each-series@1.1.0 
  │ │ ├─┬ rimraf@2.5.2 
  │ │ │ └─┬ glob@7.0.3 
  │ │ │   ├─┬ inflight@1.0.5 
  │ │ │   │ └── wrappy@1.0.2 
  │ │ │   ├─┬ minimatch@3.0.0 
  │ │ │   │ └─┬ brace-expansion@1.1.4 
  │ │ │   │   ├── balanced-match@0.4.1 
  │ │ │   │   └── concat-map@0.0.1 
  │ │ │   ├── once@1.3.3 
  │ │ │   └── path-is-absolute@1.0.0 
  │ │ └─┬ url-regex@3.1.1 
  │ │   └── ip-regex@1.0.3 
  │ ├─┬ bin-wrapper@3.0.2 
  │ │ ├─┬ bin-check@2.0.0 
  │ │ │ └─┬ executable@1.1.0 
  │ │ │   └─┬ meow@3.7.0 
  │ │ │     ├─┬ camelcase-keys@2.1.0 
  │ │ │     │ └── camelcase@2.1.1 
  │ │ │     ├── decamelize@1.2.0 
  │ │ │     ├─┬ loud-rejection@1.3.0 
  │ │ │     │ ├── array-find-index@1.0.1 
  │ │ │     │ └── signal-exit@2.1.2 
  │ │ │     ├── map-obj@1.0.1 
  │ │ │     ├─┬ normalize-package-data@2.3.5 
  │ │ │     │ ├── hosted-git-info@2.1.5 
  │ │ │     │ ├─┬ is-builtin-module@1.0.0 
  │ │ │     │ │ └── builtin-modules@1.1.1 
  │ │ │     │ └─┬ validate-npm-package-license@3.0.1 
  │ │ │     │   ├─┬ spdx-correct@1.0.2 
  │ │ │     │   │ └── spdx-license-ids@1.2.1 
  │ │ │     │   └─┬ spdx-expression-parse@1.0.2 
  │ │ │     │     └── spdx-exceptions@1.0.4 
  │ │ │     ├── object-assign@4.1.0 
  │ │ │     ├─┬ read-pkg-up@1.0.1 
  │ │ │     │ ├─┬ find-up@1.1.2 
  │ │ │     │ │ └── path-exists@2.1.0 
  │ │ │     │ └─┬ read-pkg@1.1.0 
  │ │ │     │   ├── load-json-file@1.1.0 
  │ │ │     │   └── path-type@1.1.0 
  │ │ │     ├─┬ redent@1.0.0 
  │ │ │     │ ├─┬ indent-string@2.1.0 
  │ │ │     │ │ └─┬ repeating@2.0.1 
  │ │ │     │ │   └─┬ is-finite@1.0.1 
  │ │ │     │ │     └── number-is-nan@1.0.0 
  │ │ │     │ └── strip-indent@1.0.1 
  │ │ │     └── trim-newlines@1.0.0 
  │ │ ├─┬ bin-version-check@2.1.0 
  │ │ │ ├─┬ bin-version@1.0.4 
  │ │ │ │ └─┬ find-versions@1.2.1 
  │ │ │ │   └── semver-regex@1.0.0 
  │ │ │ ├── minimist@1.2.0 
  │ │ │ ├── semver@4.3.6 
  │ │ │ └─┬ semver-truncate@1.1.0 
  │ │ │   └── semver@5.1.0 
  │ │ ├─┬ each-async@1.1.1 
  │ │ │ ├── onetime@1.1.0 
  │ │ │ └── set-immediate-shim@1.0.1 
  │ │ ├── lazy-req@1.1.0 
  │ │ └── os-filter-obj@1.0.3 
  │ └─┬ logalot@2.1.0 
  │   ├─┬ figures@1.7.0 
  │   │ ├── escape-string-regexp@1.0.5 
  │   │ └── object-assign@4.1.0 
  │   └─┬ squeak@1.3.0 
  │     ├─┬ chalk@1.1.3 
  │     │ ├── ansi-styles@2.2.1 
  │     │ ├─┬ has-ansi@2.0.0 
  │     │ │ └── ansi-regex@2.0.0 
  │     │ ├── strip-ansi@3.0.1 
  │     │ └── supports-color@2.0.0 
  │     ├── console-stream@0.1.1 
  │     └─┬ lpad-align@1.1.0 
  │       ├── get-stdin@4.0.1 
  │       ├── longest@1.0.1 
  │       └── lpad@2.0.1 
  ├─┬ exec-buffer@3.0.0 
  │ ├─┬ execa@0.3.0 
  │ │ ├─┬ cross-spawn-async@2.2.4 
  │ │ │ ├─┬ lru-cache@4.0.1 
  │ │ │ │ ├── pseudomap@1.0.2 
  │ │ │ │ └── yallist@2.0.0 
  │ │ │ └─┬ which@1.2.9 
  │ │ │   └── isexe@1.1.2 
  │ │ ├── npm-run-path@1.0.0 
  │ │ ├── object-assign@4.1.0 
  │ │ ├── path-key@1.0.0 
  │ │ └── strip-eof@1.0.0 
  │ ├── pify@2.3.0 
  │ └─┬ tempfile@1.1.1 
  │   ├── os-tmpdir@1.0.1 
  │   └── uuid@2.0.2 
  └─┬ is-cwebp-readable@1.0.3 
    └── file-type@3.8.0 
```

**Comment by thisconnect** [comment]
Do you want me to setup a test repo?

**Comment by thisconnect** [comment]
sorry I have to leave for today.

**Comment by kevva** [comment]
You could just send paste the image here and I'll try it.

**Comment by thisconnect** [comment]
found another cafe... just wanted to say, with buffer webp works of corse. But the readme example https://github.com/imagemin/imagemin-webp#usage does not use buffer. Should the example be updated to use buffer or should this example actually write .webp file endings?

**Comment by kevva** [comment]
That example should write `.webp` files, yes. Can you share the image?

**Comment by thisconnect** [comment]
Yes sorry. I am testing with 
https://pbs.twimg.com/profile_images/710428065369890816/ZaHBODSJ.jpg
and https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB.png

purposely using a jpg with text to easily see the compression and a png with gradients

**Comment by thisconnect** [comment]
This is my example code
```javascript
const imagemin = require('imagemin');
const imageminWebp = require('imagemin-webp');

imagemin(['images/*.{jpg,png}'], 'build', {
  use: [imageminWebp({
    // quality: 80,
    // preset: 'default',
    // method: 6,
    // autoFilter: true
  })]
})
.then(() => {
  console.log('Images optimized');
})
.catch(err => {
  console.log(err)
});
```

**Comment by kevva** [comment]
Should be fixed in https://github.com/imagemin/imagemin/commit/26466f4ec3cf45b3be3fc9d7cf1cc376d256ac57.

**Comment by thisconnect** [comment]
Great, thanks again!!!!!

I think it works as expected. If 2 files have the same name and different file extension, i.e. `image.png` and `image.jpg` it would overwrite one or the other, as both would result into `image.webp`. IMO this is ok. One could use the buffer api directly.

**Comment by Soheevich** [comment]
Should it work with gulp (version 3.9.1)? I'm a total newbie and maybe doing something wrong. But extensions don't change.

const imagemin = require("gulp-imagemin");
const imageminWebp = require("imagemin-webp");

gulp.task("imagemin", () =>
  gulp
    .src("src/images/*.{jpg,png}")
    .pipe(imagemin([imageminWebp()]))
    .pipe(gulp.dest("dist/images"))
);

**Comment by ThisNameWasTaken** [comment]
I solved this issue by doing this

```js
const gulp = require('gulp');
const rename = require('gulp-rename');
const imagemin = require('gulp-imagemin');
const webp = require('imagemin-webp');

gulp.task('webp-convert', () =>
    gulp.src(`src/images/*.{jpeg,jpg,png,JPEG,JPG,PNG}`)
        .pipe(rename({ extname: '.webp' }))
        .pipe(imagemin([webp()]))
        .pipe(gulp.dest('dist/images'))
);
```

**Comment by kronos93** [comment]
I have the same issue with the next files.
I don't know if it is because the images has transparency.
I tried with gulp and it works but with imagemin and their plugins not.

![marathons-logo](https://user-images.githubusercontent.com/8199459/43546836-3b53ca78-959f-11e8-9bfe-bdfed496e8ce.png)
![maratones-berlin-logo](https://user-images.githubusercontent.com/8199459/43546837-3b6583f8-959f-11e8-87fb-c9dfcf908901.png)
![maratones-chicago-logo](https://user-images.githubusercontent.com/8199459/43546838-3b792a02-959f-11e8-809b-7fa03c06c13a.png)
![maratones-new-york-logo](https://user-images.githubusercontent.com/8199459/43546839-3b892dc6-959f-11e8-9121-12dadf13b4ec.jpg)
![berlin-logo](https://user-images.githubusercontent.com/8199459/43546869-5108dbf6-959f-11e8-88a3-1ce1887bf49f.png)
![chicago-logo](https://user-images.githubusercontent.com/8199459/43546870-511a72d0-959f-11e8-88dd-cfa23091c37e.png)
![londres-logo](https://user-images.githubusercontent.com/8199459/43546872-512aafc4-959f-11e8-8076-5cba2832e185.png)
![new-york-logo](https://user-images.githubusercontent.com/8199459/43546873-513b7304-959f-11e8-951b-65dfea003f52.png)
![top-ten-femenil](https://user-images.githubusercontent.com/8199459/43546874-514cf5de-959f-11e8-95ce-24444562f324.png)
![top-ten-varonil](https://user-images.githubusercontent.com/8199459/43546875-515c6db6-959f-11e8-93b2-5449f4b5e564.png)
![webpack](https://user-images.githubusercontent.com/8199459/43546884-560642f6-959f-11e8-82d7-caefd3fa9a08.png)

**Comment by MuneebRabaney** [comment]
```
const gulp = require("gulp");
const imagemin = require("gulp-imagemin");
const extReplace = require("gulp-ext-replace");
const webp = require("imagemin-webp");

// Simple task to convert png to webp
gulp.task("images:webp", function() {
  const stream = gulp
    .src("./public/images/**/*.png")
    .pipe(
      imagemin({
        verbose: true,
        plugins: webp({ quality: 70 })
      })
    )
    .pipe(extReplace(".webp"))
    .pipe(gulp.dest("./public/images"));
  return stream;
});
```

Just add `gulp-ext-replace` and use it the way im using it in the above snippet :)
